### ISSUE TITLE
チームでの開発課題を決める

### ISSUE THREAD

**Issue by tantan5** [tantan5/z15014am_gem#1]
# 今のところのアイディア
- [ ] 入力に応じて文字列がかえる
- [ ] 時間に応じて挨拶がかえる
- [x] 面数と個数でサイコロ振った結果

**Comment by terra-yucco** [comment]
15:30くらいまでには一回題材決めたいですね！

**Comment by tantan5** [comment]
サイコロいいですね！

**Comment by Kamihara** [comment]
サイコロに一票です！

**Comment by tantan5** [comment]
サイコロで決定しましょう #1
