### ISSUE TITLE
6面サイコロを1つ振るメソッドを作る

### ISSUE THREAD

**Issue by tantan5** [tantan5/z15014am_gem#2]

**Comment by terra-yucco** [comment]
# 決めること
モジュール名
クラス名
メソッド名
I/F(引数、戻り値)

**Comment by terra-yucco** [comment]
モジュール名 Z15014amGem
クラス名 Dice
メソッド名 six_sided_dice
返却値 int(1-6？)

@Kamihara こんな感じでどうでしょうか？
メソッド名とかはここを参考にしました
http://qiita.com/oshou/items/b7873c67cf22b5e8b42f

**Comment by terra-yucco** [comment]
クラス名Diceだからsix_sidedでいいかもしれないと自己レス。
1個っていうの明示した方がいいですかね。
cast_one_six_sided

クラス名とセットでないとわからない例 :sweat:

**Comment by Kamihara** [comment]
了解しました！
メソッド名はcast_one_six_sided
戻り値はint(1-6)で進めます

**Comment by terra-yucco** [comment]
かしこまりましたー！よろしくお願いします！
