### ISSUE TITLE
Travis CIとの連携

### ISSUE THREAD

**Issue by terra-yucco** [tantan5/z15014am_gem#4]
@tantan5 
よろしくお願いします！
※今はRedになるはず

**Comment by terra-yucco** [comment]
たぶん設定だけならすぐ終わってしまうので、
その後のgemspecの修正も合わせてお願いできればと思います。

**Comment by tantan5** [comment]
@terra-yucco 
Servicesにグリーンのチェックがつきましたが、これで連携の設定完了の認識で良いんですかね？
gemspecの修正の件了解です。

**Comment by terra-yucco** [comment]
@tantan5 
大丈夫ではないかと思います！
gemspec修正をpushした時に動くかわかると思います

**Comment by tantan5** [comment]
#
